### ISSUE TITLE
Any chance of an update ?

### ISSUE THREAD

**Issue by zzedmore** [RobLoach/libretro-database-cht-spectrum#1]
@RobLoach Hi, any chance of updating these ? And/or is there an easy way that I could batch convert these POK to CHT on Windows ? The reason I ask is because a lot of the names are wrong (in the TOSEC and ladyeklipse naming) or using the Alternate name that nobody recognizes. Thanks for your work.

**Comment by RobLoach** [comment]
Ooo! Didn't know some updates came in :smile:

**Comment by RobLoach** [comment]
Updated over at https://github.com/libretro/libretro-database/pull/1152

**Comment by zzedmore** [comment]
@RobLoach Thanks for the quick update !! Is there any way for your script to work on Windows so I can convert my own collection of POK files to CHT ?

**Comment by RobLoach** [comment]
As long as you install Node.js, and get the git submodules checked out, it should work just fine:
https://nodejs.org

If you upload your POK files to a git repository, I could add them in here to convert them.

**Comment by zzedmore** [comment]
I managed to get most of them using a fuzzy match. Thanks for your help anyway. :)

**Comment by RobLoach** [comment]
Woo! How did you fuzzy match them?

**Comment by zzedmore** [comment]
I think it was called Fuzzy Rename. It matched quite a few of the CHTs to the filenames I have, not entirely sure its accurate though. 
The recent TOSEC Spectrum sets have decided to use the alternate names for the games so some have completely different names which is why I wanted to match them for my personal collection.

I did try to create a repo and upload mine to see if you could convert them for me with your script but it said I could only upload 100 files at a time so I gave up !

Ultimately it would be good if I could convert the POK to CHT on Windows or Raspberry Pi with a script that would read one location/folder and output to another.

I may ask the author of the tool 'Pokemaster' who also did the Spectrum TOSEC set and see if she can add it to her program, but I doubt it.
